//cityList里面包含了各省省会，包括直辖市
export const cityList = [
  { label: '北京', prop: 'beijing' },
  { label: '天津', prop: 'tianjin' },
  { label: '石家庄', prop: 'shijiazhuang' },
  { label: '太原', prop: 'taiyuan' },
  { label: '呼和浩特', prop: 'huhehaote' },
  { label: '沈阳', prop: 'shenyang' },
  { label: '长春', prop: 'changchun' },
  { label: '哈尔滨', prop: 'haerbin' },
  { label: '上海', prop: 'shanghai' },
  { label: '南京', prop: 'nanjing' },
  { label: '杭州', prop: 'hangzhou' },
  { label: '合肥', prop: 'hefei' },
  { label: '厦门', prop: 'xiamen' },
  { label: '南昌', prop: 'nanchang' },
  { label: '济南', prop: 'jinan' },
  { label: '郑州', prop: 'zhengzhou' },
  { label: '武汉', prop: 'wuhan' },
  { label: '长沙', prop: 'changsha' },
  { label: '广州', prop: 'guangzhou' },
  { label: '南宁', prop: 'nanning' },
  { label: '海口', prop: 'haikou' },
  { label: '重庆', prop: 'chongqing' },
  { label: '成都', prop: 'chengdu' },
  { label: '贵阳', prop: 'guiyang' },
  { label: '昆明', prop: 'kunming' },
  { label: '拉萨', prop: 'lasa' },
  { label: '西安', prop: 'xian' },
  { label: '兰州', prop: 'lanzhou' },
  { label: '西宁', prop: 'xining' },
  { label: '银川', prop: 'yinchuan' },
  { label: '乌鲁木齐', prop: 'wulumuqi' }
]
