//cityList里面包含了各省省会，包括直辖市
export const cityList = [
  { label: '北京', prop: 'beijing', width: '120' },
  { label: '天津', prop: 'tianjin', width: '120' },
  { label: '石家庄', prop: 'shijiazhuang', width: '120' },
  { label: '太原', prop: 'taiyuan', width: '120' },
  { label: '呼和浩特', prop: 'huhehaote', width: '120' },
  { label: '沈阳', prop: 'shenyang', width: '120' },
  { label: '长春', prop: 'changchun', width: '120' },
  { label: '哈尔滨', prop: 'haerbin', width: '120' },
  { label: '上海', prop: 'shanghai', width: '120' },
  { label: '南京', prop: 'nanjing', width: '120' },
  { label: '杭州', prop: 'hangzhou', width: '120' },
  { label: '合肥', prop: 'hefei', width: '120' },
  { label: '厦门', prop: 'xiamen', width: '120' },
  { label: '南昌', prop: 'nanchang', width: '120' },
  { label: '济南', prop: 'jinan', width: '120' },
  { label: '郑州', prop: 'zhengzhou', width: '120' },
  { label: '武汉', prop: 'wuhan', width: '120' },
  { label: '长沙', prop: 'changsha', width: '120' },
  { label: '广州', prop: 'guangzhou', width: '120' },
  { label: '南宁', prop: 'nanning', width: '120' },
  { label: '海口', prop: 'haikou', width: '120' },
  { label: '重庆', prop: 'chongqing', width: '120' },
  { label: '成都', prop: 'chengdu', width: '120' },
  { label: '贵阳', prop: 'guiyang', width: '120' },
  { label: '昆明', prop: 'kunming', width: '120' },
  { label: '拉萨', prop: 'lasa', width: '120' },
  { label: '西安', prop: 'xian', width: '120' },
  { label: '兰州', prop: 'lanzhou', width: '120' },
  { label: '西宁', prop: 'xining', width: '120' },
  { label: '银川', prop: 'yinchuan', width: '120' },
  { label: '乌鲁木齐', prop: 'wulumuqi', width: '120' }
]
